import { Inter } from 'next/font/google';

import './globals.css';
import Footer from './components/common/Footer';
import Header from './components/common/Header';
import ScrollToTop from './components/common/ScrollToTop';
import SmoothScroll from './smooth-scroll';

import type { Metadata } from 'next';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: '极简一生 | TROJAN 的个人网站',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`min-h-screen flex flex-col items-center text-black font-normal leading-none`}
      >
        <SmoothScroll>
          <Header />
          <main className="w-[1200px] flex-1 mt-20 pb-12">{children}</main>
          <Footer />

          <ScrollToTop className="fixed bottom-3 left-[calc(50vw+600px+16px)]" />
        </SmoothScroll>
      </body>
    </html>
  );
}
